// Diretório da Rede Moura — usado só no cadastro de distribuidor (Super Admin).
// ATENÇÃO: dado sensível. Este módulo é SERVER-ONLY: importe-o apenas em
// componentes de servidor protegidos por requireAdmin (ex.: admin/page.tsx) e
// repasse ao cliente por props. NÃO importe em arquivos "use client" — isso o
// colocaria no bundle público. Gerado a partir do CSV do diretório.

export type MouraEntry = {
  id: string
  regiao: string
  uf: string
  cidade: string
  unidade: string
  razaoSocial: string
  tipo: string
  responsavel: string
  telefone: string
  email: string
}

export const mouraDirectory: MouraEntry[] = [
  {
    "id": "avic-1",
    "regiao": "Sul",
    "uf": "PR",
    "cidade": "Curitiba",
    "unidade": "AVIC",
    "razaoSocial": "AVIC Distribuidora de Acumuladores Ltda",
    "tipo": "Matriz",
    "responsavel": "Walter Sales",
    "telefone": "(41) 3301 9500",
    "email": "walter.sales@bateriasmoura.com"
  },
  {
    "id": "avic-filial-guarapuava-2",
    "regiao": "Sul",
    "uf": "PR",
    "cidade": "Guarapuava",
    "unidade": "AVIC Filial Guarapuava",
    "razaoSocial": "AVIC Distribuidora de Acumuladores Ltda",
    "tipo": "Filial",
    "responsavel": "Conrado Gorniak",
    "telefone": "(42) 3622 0344",
    "email": "conrado.gorniak@bateriasmoura.com"
  },
  {
    "id": "batermol-3",
    "regiao": "Sul",
    "uf": "PR",
    "cidade": "Londrina",
    "unidade": "BATERMOL",
    "razaoSocial": "Batermol Distribuidor Paranaense de Acumuladores Ltda",
    "tipo": "Matriz",
    "responsavel": "Alessandra Cavalcanti",
    "telefone": "(43) 3329 6904",
    "email": ""
  },
  {
    "id": "campos-gerais-4",
    "regiao": "Sul",
    "uf": "PR",
    "cidade": "Ponta Grossa",
    "unidade": "CAMPOS GERAIS",
    "razaoSocial": "Campos Gerais Comércio de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Kamila Maria",
    "telefone": "(42) 3243 1008",
    "email": ""
  },
  {
    "id": "cascavel-5",
    "regiao": "Sul",
    "uf": "PR",
    "cidade": "Cascavel",
    "unidade": "CASCAVEL",
    "razaoSocial": "Cascavel Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Nataly Neres",
    "telefone": "(45) 3197 0602",
    "email": ""
  },
  {
    "id": "joinville-6",
    "regiao": "Sul",
    "uf": "SC",
    "cidade": "Araquari (Joinville)",
    "unidade": "JOINVILLE",
    "razaoSocial": "Joinville Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Audrey Gomes",
    "telefone": "(47) 3307 8085",
    "email": "audrey.gomes@bateriasmoura.com"
  },
  {
    "id": "catarinense-7",
    "regiao": "Sul",
    "uf": "SC",
    "cidade": "Palhoça",
    "unidade": "CATARINENSE",
    "razaoSocial": "Distribuidora Catarinense de Acumuladores Ltda",
    "tipo": "Matriz",
    "responsavel": "Tiago Furlanetto",
    "telefone": "(48) 3341 2654",
    "email": "tiago.furlanetto@bateriasmoura.com"
  },
  {
    "id": "blumenau-8",
    "regiao": "Sul",
    "uf": "SC",
    "cidade": "Blumenau",
    "unidade": "BLUMENAU",
    "razaoSocial": "Blumenau Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Ricardo Graf",
    "telefone": "(47) 3285 2778",
    "email": "ricardo.graf@bateriasmoura.com"
  },
  {
    "id": "criciuma-9",
    "regiao": "Sul",
    "uf": "SC",
    "cidade": "Içara (Criciúma)",
    "unidade": "CRICIÚMA",
    "razaoSocial": "Criciúma Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Bruno Moura",
    "telefone": "(48) 3462 8849",
    "email": "bruno.moura@bateriasmoura.com"
  },
  {
    "id": "chapecoense-10",
    "regiao": "Sul",
    "uf": "SC",
    "cidade": "Chapecó",
    "unidade": "CHAPECOENSE",
    "razaoSocial": "Chapecoense Comércio de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Thomás Muller",
    "telefone": "(49) 3025 7071",
    "email": "thomas.muller@bateriasmoura.com"
  },
  {
    "id": "chapecoense-filial-lages-11",
    "regiao": "Sul",
    "uf": "SC",
    "cidade": "Lages",
    "unidade": "CHAPECOENSE Filial Lages",
    "razaoSocial": "Chapecoense Comércio de Baterias Ltda",
    "tipo": "Filial",
    "responsavel": "Thiago Dias",
    "telefone": "(49) 3223 1301",
    "email": "thiago.dias@bateriasmoura.com"
  },
  {
    "id": "rodmaster-12",
    "regiao": "Sul",
    "uf": "RS",
    "cidade": "Porto Alegre",
    "unidade": "RODMASTER",
    "razaoSocial": "Rodmaster Comércio e Representante de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Vitor Oliveira",
    "telefone": "(51) 2126 6200",
    "email": "vitor.oliveira@bateriasmoura.com"
  },
  {
    "id": "rodmaster-filial-pelotas-13",
    "regiao": "Sul",
    "uf": "RS",
    "cidade": "Pelotas",
    "unidade": "RODMASTER Filial Pelotas",
    "razaoSocial": "Rodmaster Comércio e Representante de Baterias Ltda",
    "tipo": "Filial",
    "responsavel": "Daniel Correa",
    "telefone": "(53) 3283 6796",
    "email": "daniel.correa@bateriasmoura.com"
  },
  {
    "id": "caxias-do-sul-14",
    "regiao": "Sul",
    "uf": "RS",
    "cidade": "Caxias do Sul",
    "unidade": "CAXIAS DO SUL",
    "razaoSocial": "Caxias do Sul Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Luis Campos",
    "telefone": "(54) 3238 2197",
    "email": "luis.campos@bateriasmoura.com"
  },
  {
    "id": "santa-maria-15",
    "regiao": "Sul",
    "uf": "RS",
    "cidade": "Santa Maria",
    "unidade": "SANTA MARIA",
    "razaoSocial": "Santa Maria Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Luciano Maroneze",
    "telefone": "(55) 3286 1256",
    "email": "luciano.maroneze@bateriasmoura.com"
  },
  {
    "id": "santa-maria-filial-passo-fundo-16",
    "regiao": "Sul",
    "uf": "RS",
    "cidade": "Passo Fundo",
    "unidade": "SANTA MARIA Filial Passo Fundo",
    "razaoSocial": "Santa Maria Distribuidora de Baterias Ltda",
    "tipo": "Filial",
    "responsavel": "Ademilson Bernardi",
    "telefone": "(54) 3314 3023",
    "email": "ademilson.bernardi@bateriasmoura.com"
  },
  {
    "id": "belo-jardim-17",
    "regiao": "Sudeste",
    "uf": "SP",
    "cidade": "São José do Rio Preto",
    "unidade": "BELO JARDIM",
    "razaoSocial": "Belo Jardim Comercial de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Samuel Gonçalves",
    "telefone": "(17) 3224 1364",
    "email": "samuel.fernandes@bateriasmoura.com"
  },
  {
    "id": "bandeirantes-18",
    "regiao": "Sudeste",
    "uf": "SP",
    "cidade": "Campinas",
    "unidade": "BANDEIRANTES",
    "razaoSocial": "Comercial Bandeirantes de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Paulo Stoppa",
    "telefone": "(19) 3749 8830",
    "email": ""
  },
  {
    "id": "sorocaba-19",
    "regiao": "Sudeste",
    "uf": "SP",
    "cidade": "Sorocaba",
    "unidade": "SOROCABA",
    "razaoSocial": "Sorocaba Comércio de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Luis Gelotti",
    "telefone": "(15) 3233 8353",
    "email": ""
  },
  {
    "id": "anhanguera-20",
    "regiao": "Sudeste",
    "uf": "SP",
    "cidade": "Piracicaba",
    "unidade": "ANHANGUERA",
    "razaoSocial": "Comércio Anhanguera Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Felipe Lubambo",
    "telefone": "",
    "email": "felipe.lubambo@bateriasmoura.com"
  },
  {
    "id": "bauru-21",
    "regiao": "Sudeste",
    "uf": "SP",
    "cidade": "Bauru",
    "unidade": "BAURU",
    "razaoSocial": "Bauru Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Anderson Tenan",
    "telefone": "(14) 3281 6767",
    "email": "anderson.tenan@bateriasmoura.com"
  },
  {
    "id": "presidente-prudente-22",
    "regiao": "Sudeste",
    "uf": "SP",
    "cidade": "Presidente Prudente",
    "unidade": "PRESIDENTE PRUDENTE",
    "razaoSocial": "Presidente Prudente Comércio de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Juliano Moura",
    "telefone": "(18) 3928 6148",
    "email": "juliano.moura@bateriasmoura.com"
  },
  {
    "id": "dirpal-23",
    "regiao": "Sudeste",
    "uf": "SP",
    "cidade": "Ribeirão Preto",
    "unidade": "DIRPAL",
    "razaoSocial": "Dirpal Distribuidor Ribeirão Preto de Acumuladores Ltda",
    "tipo": "Matriz",
    "responsavel": "Ivan Amorim",
    "telefone": "(16) 3797 7100",
    "email": "ivan.amorim@bateriasmoura.com"
  },
  {
    "id": "sao-carlos-24",
    "regiao": "Sudeste",
    "uf": "SP",
    "cidade": "São Carlos",
    "unidade": "SÃO CARLOS",
    "razaoSocial": "São Carlos Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Claudio Pereira Peres",
    "telefone": "",
    "email": "claudio.peres@bateriasmoura.com"
  },
  {
    "id": "paulista-25",
    "regiao": "Sudeste",
    "uf": "SP",
    "cidade": "São Paulo",
    "unidade": "PAULISTA",
    "razaoSocial": "Comercial Paulista de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Petraccone Ribeiro",
    "telefone": "(11) 2967 8068",
    "email": "petraccone.ribeiro@bateriasmoura.com"
  },
  {
    "id": "osasco-26",
    "regiao": "Sudeste",
    "uf": "SP",
    "cidade": "Osasco",
    "unidade": "OSASCO",
    "razaoSocial": "Osasco Comércio de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Ricardo Souza",
    "telefone": "(11) 3695 0253",
    "email": "ricardo.souza@bateriasmoura.com"
  },
  {
    "id": "campo-limpo-27",
    "regiao": "Sudeste",
    "uf": "SP",
    "cidade": "Taboão da Serra",
    "unidade": "CAMPO LIMPO",
    "razaoSocial": "Campo Limpo Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Diogo Grassi",
    "telefone": "(11) 5812 3722",
    "email": "diogo.grassi@bateriasmoura.com"
  },
  {
    "id": "itaquera-28",
    "regiao": "Sudeste",
    "uf": "SP",
    "cidade": "São Paulo",
    "unidade": "ITAQUERA",
    "razaoSocial": "Itaquera Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Simone Sarti",
    "telefone": "(11) 5043 3237",
    "email": "simone.sarti@bateriasmoura.com"
  },
  {
    "id": "serve-vale-29",
    "regiao": "Sudeste",
    "uf": "SP",
    "cidade": "São José dos Campos",
    "unidade": "SERVE VALE",
    "razaoSocial": "Serve Vale Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Raphael Feitosa",
    "telefone": "(12) 3322 5021",
    "email": "raphael.feitosa@bateriasmoura.com"
  },
  {
    "id": "serve-vale-filial-taubate-30",
    "regiao": "Sudeste",
    "uf": "SP",
    "cidade": "Taubaté",
    "unidade": "SERVE VALE Filial Taubaté",
    "razaoSocial": "Serve Vale Baterias Ltda",
    "tipo": "Filial",
    "responsavel": "Raphael Feitosa",
    "telefone": "(12) 3681 1915",
    "email": "raphael.feitosa@bateriasmoura.com"
  },
  {
    "id": "uniao-31",
    "regiao": "Sudeste",
    "uf": "SP",
    "cidade": "Diadema",
    "unidade": "UNIÃO",
    "razaoSocial": "Comercial de Baterias União Ltda",
    "tipo": "Matriz",
    "responsavel": "Eduardo Barros",
    "telefone": "(11) 2948 1300",
    "email": "eduardo.barros@bateriasmoura.com"
  },
  {
    "id": "santos-32",
    "regiao": "Sudeste",
    "uf": "SP",
    "cidade": "Santos",
    "unidade": "SANTOS",
    "razaoSocial": "Santos Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Lehi Monteiro",
    "telefone": "(13) 3273 7554",
    "email": "lehi.monteiro@bateriasmoura.com"
  },
  {
    "id": "vila-bela-33",
    "regiao": "Sudeste",
    "uf": "SP",
    "cidade": "São Paulo",
    "unidade": "VILA BELA",
    "razaoSocial": "Vila Bela Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Douglas Bougo",
    "telefone": "",
    "email": "douglas.bougo@bateriasmoura.com"
  },
  {
    "id": "cominas-34",
    "regiao": "Sudeste",
    "uf": "MG",
    "cidade": "Belo Horizonte",
    "unidade": "COMINAS",
    "razaoSocial": "Cominas Comercial Minas de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Éder Cavalcante",
    "telefone": "(31) 3555 2750",
    "email": "eder.cavalcante@bateriasmoura.com"
  },
  {
    "id": "conorte-35",
    "regiao": "Sudeste",
    "uf": "MG",
    "cidade": "Montes Claros",
    "unidade": "CONORTE",
    "razaoSocial": "Conorte Comercial Norte Minas de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Luciano Azevedo",
    "telefone": "(38) 3215 1311",
    "email": "luciano.azevedo@bateriasmoura.com"
  },
  {
    "id": "conorte-filial-gov-valadares-36",
    "regiao": "Sudeste",
    "uf": "MG",
    "cidade": "Governador Valadares",
    "unidade": "CONORTE Filial Gov. Valadares",
    "razaoSocial": "Conorte Comercial Norte Minas de Baterias Ltda",
    "tipo": "Filial",
    "responsavel": "Dainer de Souza",
    "telefone": "(38) 9.9997-9403",
    "email": "dainer.souza@bateriasmoura.com"
  },
  {
    "id": "juiz-de-fora-37",
    "regiao": "Sudeste",
    "uf": "MG",
    "cidade": "Juiz de Fora",
    "unidade": "JUIZ DE FORA",
    "razaoSocial": "Juiz de Fora Comércio de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "João Muniz",
    "telefone": "(32) 3217 5357",
    "email": "joao.muniz@bateriasmoura.com"
  },
  {
    "id": "pocos-de-caldas-38",
    "regiao": "Sudeste",
    "uf": "MG",
    "cidade": "Poços de Caldas",
    "unidade": "POÇOS DE CALDAS",
    "razaoSocial": "Poços de Caldas Comércio de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Diogo Carlini",
    "telefone": "(35) 3713 5545",
    "email": "diogo.carlini@bateriasmoura.com"
  },
  {
    "id": "patos-de-minas-39",
    "regiao": "Sudeste",
    "uf": "MG",
    "cidade": "Patos de Minas",
    "unidade": "PATOS DE MINAS",
    "razaoSocial": "Patos de Minas Comércio de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Genival Souza",
    "telefone": "(34) 3826 2300",
    "email": "genival.souza@bateriasmoura.com"
  },
  {
    "id": "triangulo-40",
    "regiao": "Sudeste",
    "uf": "MG",
    "cidade": "Uberlândia",
    "unidade": "TRIÂNGULO",
    "razaoSocial": "Triângulo Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Rodrigo Cabral",
    "telefone": "",
    "email": "rodrigo.cabral@bateriasmoura.com"
  },
  {
    "id": "fluminense-41",
    "regiao": "Sudeste",
    "uf": "RJ",
    "cidade": "Rio de Janeiro",
    "unidade": "FLUMINENSE",
    "razaoSocial": "Comercial Fluminense de Baterias e Placas Ltda",
    "tipo": "Matriz",
    "responsavel": "Paulo Borges",
    "telefone": "(21) 2594 3298",
    "email": "paulo.borges@bateriasmoura.com"
  },
  {
    "id": "fluminense-filial-campo-grande-42",
    "regiao": "Sudeste",
    "uf": "RJ",
    "cidade": "Rio de Janeiro",
    "unidade": "FLUMINENSE Filial Campo Grande",
    "razaoSocial": "Comercial Fluminense de Baterias e Placas Ltda",
    "tipo": "Filial",
    "responsavel": "Indaraci Gonçalves",
    "telefone": "(21) 2146 5276",
    "email": "indaraci.goncalves@bateriasmoura.com"
  },
  {
    "id": "dinil-43",
    "regiao": "Sudeste",
    "uf": "RJ",
    "cidade": "Niterói",
    "unidade": "DINIL",
    "razaoSocial": "Dinil Distribuidor Niterói de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "André Lira",
    "telefone": "(21) 2621 7070",
    "email": "andre.lira@bateriasmoura.com"
  },
  {
    "id": "dinil-filial-campos-44",
    "regiao": "Sudeste",
    "uf": "RJ",
    "cidade": "Campos dos Goytacazes",
    "unidade": "DINIL Filial Campos",
    "razaoSocial": "Dinil Distribuidor Niterói de Baterias Ltda",
    "tipo": "Filial",
    "responsavel": "Fabiana Rodrigues",
    "telefone": "(21) 2621 7070",
    "email": "fabiana.rodrigues@bateriasmoura.com"
  },
  {
    "id": "nova-iguacu-45",
    "regiao": "Sudeste",
    "uf": "RJ",
    "cidade": "Nova Iguaçu",
    "unidade": "NOVA IGUAÇU",
    "razaoSocial": "Nova Iguaçu Comércio de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Rodrigo Pimentel",
    "telefone": "(21) 2768 7669",
    "email": "rodrigo.opimentel@bateriasmoura.com"
  },
  {
    "id": "volta-redonda-46",
    "regiao": "Sudeste",
    "uf": "RJ",
    "cidade": "Volta Redonda",
    "unidade": "VOLTA REDONDA",
    "razaoSocial": "Volta Redonda Comércio de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Cristiano Canuto",
    "telefone": "(24) 3342 5521",
    "email": "cristiano.canuto@bateriasmoura.com"
  },
  {
    "id": "comal-47",
    "regiao": "Sudeste",
    "uf": "ES",
    "cidade": "Serra",
    "unidade": "COMAL",
    "razaoSocial": "Comal Comercial de Acumuladores e Componentes Ltda",
    "tipo": "Matriz",
    "responsavel": "Terêncio Mello",
    "telefone": "(27) 3321 7555",
    "email": "terencio.mello@bateriasmoura.com"
  },
  {
    "id": "comal-filial-cachoeiro-48",
    "regiao": "Sudeste",
    "uf": "ES",
    "cidade": "Cachoeiro de Itapemirim",
    "unidade": "COMAL Filial Cachoeiro",
    "razaoSocial": "Comal Comercial de Acumuladores e Componentes Ltda",
    "tipo": "Filial",
    "responsavel": "Hugo de Almeida",
    "telefone": "(28) 3521 3064",
    "email": "hugo.almeida@bateriasmoura.com"
  },
  {
    "id": "comal-filial-linhares-49",
    "regiao": "Sudeste",
    "uf": "ES",
    "cidade": "Linhares",
    "unidade": "COMAL Filial Linhares",
    "razaoSocial": "Comal Comercial de Acumuladores e Componentes Ltda",
    "tipo": "Filial",
    "responsavel": "Adson Bezerra",
    "telefone": "(27) 3151 7555",
    "email": "adson.bezerra@bateriasmoura.com"
  },
  {
    "id": "brasiliense-50",
    "regiao": "Sudeste",
    "uf": "DF",
    "cidade": "Brasília",
    "unidade": "BRASILIENSE",
    "razaoSocial": "Distribuidora Brasiliense de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Leandro Stoppa",
    "telefone": "(61) 3234 3515",
    "email": "leandro.stoppa@bateriasmoura.com"
  },
  {
    "id": "godal-51",
    "regiao": "Centro-Oeste",
    "uf": "GO",
    "cidade": "Goiânia",
    "unidade": "GODAL",
    "razaoSocial": "Godal Goiás Distribuidor de Acumuladores Ltda",
    "tipo": "Matriz",
    "responsavel": "Manoel Júnior",
    "telefone": "(62) 3295 1441",
    "email": "manoel.junior@bateriasmoura.com"
  },
  {
    "id": "anapolis-52",
    "regiao": "Centro-Oeste",
    "uf": "GO",
    "cidade": "Anápolis",
    "unidade": "ANÁPOLIS",
    "razaoSocial": "Anápolis Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Victor Alves",
    "telefone": "(62) 3324 5156",
    "email": ""
  },
  {
    "id": "campo-grande-53",
    "regiao": "Centro-Oeste",
    "uf": "MS",
    "cidade": "Campo Grande",
    "unidade": "CAMPO GRANDE",
    "razaoSocial": "Campo Grande Distribuidor de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Rafael Lemos",
    "telefone": "(67) 3045 2042",
    "email": "rafael.lemos@bateriasmoura.com"
  },
  {
    "id": "campo-grande-filial-dourados-54",
    "regiao": "Centro-Oeste",
    "uf": "MS",
    "cidade": "Dourados",
    "unidade": "CAMPO GRANDE Filial Dourados",
    "razaoSocial": "Campo Grande Distribuidor de Baterias Ltda",
    "tipo": "Filial",
    "responsavel": "Danniel Duarte",
    "telefone": "(67) 3425 0651",
    "email": "danniel.duarte@bateriasmoura.com"
  },
  {
    "id": "disbac-55",
    "regiao": "Centro-Oeste",
    "uf": "MT",
    "cidade": "Cuiabá",
    "unidade": "DISBAC",
    "razaoSocial": "Disbac Distribuidor de Baterias e Componentes Ltda",
    "tipo": "Matriz",
    "responsavel": "Rafael Mendes",
    "telefone": "(65) 3627 3277",
    "email": "rafael.mendes@bateriasmoura.com"
  },
  {
    "id": "sinop-56",
    "regiao": "Centro-Oeste",
    "uf": "MT",
    "cidade": "Sinop",
    "unidade": "SINOP",
    "razaoSocial": "Sinop Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Leonardo Paiva",
    "telefone": "(66) 3532 6565",
    "email": "leonardo.paiva@bateriasmoura.com"
  },
  {
    "id": "alagoana-57",
    "regiao": "Nordeste",
    "uf": "AL",
    "cidade": "Maceió",
    "unidade": "ALAGOANA",
    "razaoSocial": "Distribuidora Alagoana de Baterias e Acessórios Ltda",
    "tipo": "Matriz",
    "responsavel": "Henrique Valença",
    "telefone": "(82) 3231 6530",
    "email": "arthur.lyra@bateriasmoura.com"
  },
  {
    "id": "alagoana-filial-arapiraca-58",
    "regiao": "Nordeste",
    "uf": "AL",
    "cidade": "Arapiraca",
    "unidade": "ALAGOANA Filial Arapiraca",
    "razaoSocial": "Distribuidora Alagoana de Baterias e Acessórios Ltda",
    "tipo": "Filial",
    "responsavel": "Evanderlan Barbosa",
    "telefone": "(82) 3521 5988",
    "email": "evanderlan.barbosa@bateriasmoura.com"
  },
  {
    "id": "autobate-59",
    "regiao": "Nordeste",
    "uf": "BA",
    "cidade": "Lauro de Freitas",
    "unidade": "AUTOBATE",
    "razaoSocial": "Autobate Com. de Baterias, Placas e Acessórios Ltda",
    "tipo": "Matriz",
    "responsavel": "Maurício Spinelli",
    "telefone": "(71) 3288 7211",
    "email": "mauricio.spinelli@bateriasmoura.com"
  },
  {
    "id": "itabuna-60",
    "regiao": "Nordeste",
    "uf": "BA",
    "cidade": "Itabuna",
    "unidade": "ITABUNA",
    "razaoSocial": "Itabuna Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Daniel Cavalcanti",
    "telefone": "(73) 3215 5216",
    "email": "daniel.cavalcanti@bateriasmoura.com"
  },
  {
    "id": "bonfim-61",
    "regiao": "Nordeste",
    "uf": "BA",
    "cidade": "Juazeiro",
    "unidade": "BONFIM",
    "razaoSocial": "Bonfim Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Leonardo Jurema",
    "telefone": "(74) 3611 9798",
    "email": "leonardo.jurema@bateriasmoura.com"
  },
  {
    "id": "interbahia-62",
    "regiao": "Nordeste",
    "uf": "BA",
    "cidade": "Feira de Santana",
    "unidade": "INTERBAHIA",
    "razaoSocial": "Interbahia Acumuladores Ltda",
    "tipo": "Matriz",
    "responsavel": "Valdemir Bastos",
    "telefone": "(75) 3221 3707",
    "email": "valdemir.bastos@bateriasmoura.com"
  },
  {
    "id": "interbahia-filial-barreiras-63",
    "regiao": "Nordeste",
    "uf": "BA",
    "cidade": "Barreiras",
    "unidade": "INTERBAHIA Filial Barreiras",
    "razaoSocial": "Interbahia Acumuladores Ltda",
    "tipo": "Filial",
    "responsavel": "Afonso Araújo",
    "telefone": "(77) 3613 0088",
    "email": "afonso.araujo@bateriasmoura.com"
  },
  {
    "id": "interbahia-filial-vitoria-da-conquista-64",
    "regiao": "Nordeste",
    "uf": "BA",
    "cidade": "Vitória da Conquista",
    "unidade": "INTERBAHIA Filial Vitória da Conquista",
    "razaoSocial": "Interbahia Acumuladores Ltda",
    "tipo": "Filial",
    "responsavel": "Antônio Pedreira",
    "telefone": "(77) 3426 3309",
    "email": "antonio.pedreira@bateriasmoura.com"
  },
  {
    "id": "palacio-65",
    "regiao": "Nordeste",
    "uf": "PE",
    "cidade": "Recife",
    "unidade": "PALÁCIO",
    "razaoSocial": "Palácio das Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Anderson Viana",
    "telefone": "(81) 2128 1188",
    "email": "anderson.viana@bateriasmoura.com"
  },
  {
    "id": "combat-66",
    "regiao": "Nordeste",
    "uf": "PE",
    "cidade": "Caruaru",
    "unidade": "COMBAT",
    "razaoSocial": "Combat Comércio de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Waldeir Torres",
    "telefone": "(81) 9.9987-9348",
    "email": "waldeir.torres@bateriasmoura.com"
  },
  {
    "id": "cariri-67",
    "regiao": "Nordeste",
    "uf": "CE",
    "cidade": "Barbalha",
    "unidade": "CARIRI",
    "razaoSocial": "Cariri Distribuidora de Baterias",
    "tipo": "Matriz",
    "responsavel": "Ricardo Lopes",
    "telefone": "(88) 3571 1278",
    "email": "ricardo.lopes@bateriasmoura.com"
  },
  {
    "id": "fortaleza-68",
    "regiao": "Nordeste",
    "uf": "CE",
    "cidade": "Fortaleza",
    "unidade": "FORTALEZA",
    "razaoSocial": "Fortaleza das Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "José Garibaldi da Nóbrega Júnior",
    "telefone": "(85) 3494 7522",
    "email": "garibaldi.nobrega@bateriasmoura.com"
  },
  {
    "id": "sobral-69",
    "regiao": "Nordeste",
    "uf": "CE",
    "cidade": "Sobral",
    "unidade": "SOBRAL",
    "razaoSocial": "Distribuidora Sobral de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Cristiane Caetano",
    "telefone": "(88) 3611 6040",
    "email": "cristiane.caetano@bateriasmoura.com"
  },
  {
    "id": "iguatu-70",
    "regiao": "Nordeste",
    "uf": "CE",
    "cidade": "Iguatu",
    "unidade": "IGUATU",
    "razaoSocial": "Iguatu Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Washington Pontes",
    "telefone": "(88) 3581 1626",
    "email": "washington.luis@bateriasmoura.com"
  },
  {
    "id": "codiba-71",
    "regiao": "Nordeste",
    "uf": "RN",
    "cidade": "Natal",
    "unidade": "CODIBA",
    "razaoSocial": "Codiba Comercial Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Aldo Cezar",
    "telefone": "(84) 3213 3820",
    "email": "codiba@bateriasmoura.com"
  },
  {
    "id": "paraiba-72",
    "regiao": "Nordeste",
    "uf": "PB",
    "cidade": "João Pessoa",
    "unidade": "PARAÍBA",
    "razaoSocial": "Paraíba Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Mário Bezerra",
    "telefone": "(83) 3241 2106",
    "email": "mario.bezerra@bateriasmoura.com"
  },
  {
    "id": "disbate-73",
    "regiao": "Nordeste",
    "uf": "SE",
    "cidade": "Aracaju",
    "unidade": "DISBATE",
    "razaoSocial": "Disbate Distribuidora Sergipana de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Rafael Campêlo",
    "telefone": "(79) 3021 7800",
    "email": "rafael.campelo@bateriasmoura.com"
  },
  {
    "id": "dismal-74",
    "regiao": "Nordeste",
    "uf": "MA",
    "cidade": "São Luís",
    "unidade": "DISMAL",
    "razaoSocial": "Dismal Distribuidor Maranhense de Acumuladores Ltda",
    "tipo": "Matriz",
    "responsavel": "Fredson Alves",
    "telefone": "(98) 3245 5454",
    "email": "fredson.alves@bateriasmoura.com"
  },
  {
    "id": "imperatriz-75",
    "regiao": "Nordeste",
    "uf": "MA",
    "cidade": "Imperatriz",
    "unidade": "IMPERATRIZ",
    "razaoSocial": "Distribuidora Imperatriz de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Sidney Pantoja",
    "telefone": "(99) 3523 3685",
    "email": "sidney.pantoja@bateriasmoura.com"
  },
  {
    "id": "piauiense-76",
    "regiao": "Nordeste",
    "uf": "PI",
    "cidade": "Teresina",
    "unidade": "PIAUIENSE",
    "razaoSocial": "Distribuidora Piauiense de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Antonio Guilherme",
    "telefone": "(86) 3218 2233",
    "email": "antonio.guilherme@bateriasmoura.com"
  },
  {
    "id": "norte-77",
    "regiao": "Norte",
    "uf": "AM",
    "cidade": "Manaus",
    "unidade": "NORTE",
    "razaoSocial": "Norte Distribuidora de Acumuladores e Acessórios Ltda",
    "tipo": "Matriz",
    "responsavel": "Artur César Santos",
    "telefone": "(92) 3632 5050",
    "email": "artur.santos@bateriasmoura.com"
  },
  {
    "id": "norte-filial-boa-vista-78",
    "regiao": "Norte",
    "uf": "RR",
    "cidade": "Boa Vista",
    "unidade": "NORTE Filial Boa Vista",
    "razaoSocial": "Norte Distribuidora de Acumuladores e Acessórios Ltda",
    "tipo": "Filial",
    "responsavel": "Artur César Santos",
    "telefone": "",
    "email": "artur.santos@bateriasmoura.com"
  },
  {
    "id": "paraense-79",
    "regiao": "Norte",
    "uf": "PA",
    "cidade": "Belém",
    "unidade": "PARAENSE",
    "razaoSocial": "Distribuidora Paraense de Baterias e Acessórios Ltda",
    "tipo": "Matriz",
    "responsavel": "Hudson Gomes",
    "telefone": "(91) 3233 1891",
    "email": "hudson.gomes@bateriasmoura.com"
  },
  {
    "id": "santarem-80",
    "regiao": "Norte",
    "uf": "PA",
    "cidade": "Santarém",
    "unidade": "SANTARÉM",
    "razaoSocial": "Santarém Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Rodrigo Freitas",
    "telefone": "(93) 3522 5357",
    "email": "rodrigo.freitas@bateriasmoura.com"
  },
  {
    "id": "maraba-81",
    "regiao": "Norte",
    "uf": "PA",
    "cidade": "Marabá",
    "unidade": "MARABÁ",
    "razaoSocial": "Marabá Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Edilson Nascimento",
    "telefone": "(94) 3322 4874",
    "email": "edilson.nascimento@bateriasmoura.com"
  },
  {
    "id": "macapa-82",
    "regiao": "Norte",
    "uf": "AP",
    "cidade": "Macapá",
    "unidade": "MACAPÁ",
    "razaoSocial": "Macapá Distribuidora de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Vanessa Lima",
    "telefone": "(96) 3222 8691",
    "email": "vanessa.lima@bateriasmoura.com"
  },
  {
    "id": "porto-velho-83",
    "regiao": "Norte",
    "uf": "RO",
    "cidade": "Porto Velho",
    "unidade": "PORTO VELHO",
    "razaoSocial": "Porto Velho Distribuidor de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "João Oliveira",
    "telefone": "(69) 3221 7070",
    "email": "joao.oliveira@bateriasmoura.com"
  },
  {
    "id": "tocantins-84",
    "regiao": "Norte",
    "uf": "TO",
    "cidade": "Palmas",
    "unidade": "TOCANTINS",
    "razaoSocial": "Distribuidora Tocantins de Baterias Ltda",
    "tipo": "Matriz",
    "responsavel": "Nicácio Souza",
    "telefone": "(63) 3214 5425",
    "email": "nicacio.souza@bateriasmoura.com"
  },
  {
    "id": "rede-moura-participacoes-s-a-85",
    "regiao": "Corporativo",
    "uf": "PE",
    "cidade": "Recife",
    "unidade": "Rede Moura Participações S/A",
    "razaoSocial": "Rede Moura Participações S/A",
    "tipo": "Holding",
    "responsavel": "",
    "telefone": "",
    "email": ""
  },
  {
    "id": "moura-un02-86",
    "regiao": "Corporativo",
    "uf": "PE",
    "cidade": "Jaboatão dos Guararapes",
    "unidade": "Moura UN02",
    "razaoSocial": "Moura - UN02",
    "tipo": "Unidade fabril/corporativa",
    "responsavel": "",
    "telefone": "(81) 2121 1600",
    "email": ""
  },
  {
    "id": "moura-escritorio-sao-paulo-87",
    "regiao": "Corporativo",
    "uf": "SP",
    "cidade": "São Paulo",
    "unidade": "Moura Escritório São Paulo",
    "razaoSocial": "Moura Escritório São Paulo",
    "tipo": "Escritório",
    "responsavel": "",
    "telefone": "(11) 3336 2400",
    "email": ""
  },
  {
    "id": "rm-comercial-88",
    "regiao": "Corporativo",
    "uf": "SP",
    "cidade": "São Paulo",
    "unidade": "RM Comercial",
    "razaoSocial": "RM Comercial de Produtos Automotivos Ltda",
    "tipo": "Escritório",
    "responsavel": "Felipe Godoy",
    "telefone": "(11) 2081 2814",
    "email": ""
  },
  {
    "id": "buenos-aires-89",
    "regiao": "Cone Sul",
    "uf": "AR",
    "cidade": "Ciudad Autónoma de Buenos Aires",
    "unidade": "BUENOS AIRES",
    "razaoSocial": "Moura Buenos Aires",
    "tipo": "Matriz",
    "responsavel": "Facundo Ludueña",
    "telefone": "+54 11 4524 8200",
    "email": "facundo.luduena@grupomoura.com"
  },
  {
    "id": "cordoba-90",
    "regiao": "Cone Sul",
    "uf": "AR",
    "cidade": "Córdoba",
    "unidade": "CÓRDOBA",
    "razaoSocial": "Moura Córdoba",
    "tipo": "Matriz",
    "responsavel": "Victor Nasute",
    "telefone": "+54 351 569 0984",
    "email": "victor.nasute@grupomoura.com"
  },
  {
    "id": "mar-del-plata-91",
    "regiao": "Cone Sul",
    "uf": "AR",
    "cidade": "Mar del Plata",
    "unidade": "MAR DEL PLATA",
    "razaoSocial": "Moura Mar del Plata",
    "tipo": "Matriz",
    "responsavel": "Fernando Garcia",
    "telefone": "+54 223 6265 361",
    "email": "fernando.garcia@grupomoura.com"
  },
  {
    "id": "mendoza-92",
    "regiao": "Cone Sul",
    "uf": "AR",
    "cidade": "Mendoza",
    "unidade": "MENDOZA",
    "razaoSocial": "Moura Mendoza",
    "tipo": "Matriz",
    "responsavel": "Diego Spitaleri",
    "telefone": "+54 261 662 5797",
    "email": "diego.spitaleri@grupomoura.com"
  },
  {
    "id": "rosario-93",
    "regiao": "Cone Sul",
    "uf": "AR",
    "cidade": "Rosario",
    "unidade": "ROSARIO",
    "razaoSocial": "Moura Rosario",
    "tipo": "Matriz",
    "responsavel": "Maria Grossi",
    "telefone": "+54 341 6092010",
    "email": "maria.grossi@grupomoura.com"
  },
  {
    "id": "tucuman-94",
    "regiao": "Cone Sul",
    "uf": "AR",
    "cidade": "San Miguel de Tucumán",
    "unidade": "TUCUMÁN",
    "razaoSocial": "Moura Tucumán",
    "tipo": "Matriz",
    "responsavel": "Santiago Nanni",
    "telefone": "+54 381 689 0539",
    "email": "santiago.nanni@grupomoura.com"
  },
  {
    "id": "montevideo-95",
    "regiao": "Cone Sul",
    "uf": "UY",
    "cidade": "Montevideo",
    "unidade": "MONTEVIDEO",
    "razaoSocial": "Moura Montevideo",
    "tipo": "Matriz",
    "responsavel": "Juan Spitzer",
    "telefone": "+598 2 924 8181",
    "email": "juan.spitzer@grupomoura.com"
  }
]
